### ISSUE TITLE
Change App's Meta on Store

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/windows-universal#20]
- [ ] Since the repository has changed, we should change the links given in the app's description on Windows Store 😅 

- [ ] Maybe we could also remove the stuff about that this app is "unofficial" ... its maintained in an official community repository 😉 (... @karlitschek for "legal" stuff)

- [ ] Consider about removing the "#" and "##" - it does not seem to support Markdown 😁 

- [ ] Change Support link from Gitter to GitHub Issues (...which makes more sense, since we are able to reproduce and organize bugs and issues here better)

What do you think? @SunboX

**Comment by karlitschek** [comment]
agreed!!! 👍

**Comment by LukasReschke** [comment]
>  Maybe we could also remove the stuff about that this app is "unofficial" ... its maintained in an official community repository 😉 (... @karlitschek for "legal" stuff)

I do disagree very much with that. I won't repeat myself but please check https://github.com/nextcloud/nextcloud.com/pull/260 and https://github.com/nextcloud/nextcloud.com/commit/279596b6441d0fa0ad851eefa1d1eae1549da414#commitcomment-19785094

**Comment by LukasReschke** [comment]
In a nutshell:

1. Official means "we" support it. I don't see any real contributor besides 1 external person here.
2. Official means that customers of Nextcloud GmbH will expect it to be supported and file issues. This is horrible.
3. Official means we will fix security bugs and whatever in it. Which also is not guaranteed.

That is what the public perception of official is…

**Comment by LukasReschke** [comment]
And yes, our website at the moment states that we do support Windows Mobile basically for Enterprise customers: https://github.com/nextcloud/nextcloud.com/commit/279596b6441d0fa0ad851eefa1d1eae1549da414#commitcomment-19785094

**Comment by MariusBluem** [comment]
Also if I did not talked about mention it as "official" but just not as "unofficial" ... I really see your point and must agree with you about the way customers would see it ... If anything breaks on this side here, this could hurt Nextcloud GmbH's reputation also if nothing was done wrong on their side. And this is not what anybody here wants to do 😉 We should find a way to tell people about this app, that they will test, contribute and use ... the problem is, that the only way to do this - is offering it 😜 (maybe with the biggest ALPHA-button of the world ... but however: We should!) ... I've just opened a PR on the website to remove it from Enterprise for now 😁

**Comment by SunboX** [comment]
If it's OK to you, I would change the text with the next submission like this:

> This is the Nextcloud app allowing you to access all your files on Windows Mobile (...and UWP coming soon). 
>  
> I decided to set a price of 99 cent to compensate my app store costs and maybe a little bit of my spare time in future to keep this project up to date. If you do not want to spend the money, you can download the source code from Github and build & deploy it by your own without any limitations. It's all open source. 
>  
> Features already implemented: 
> • Easy, modern interface 
> • Upload your files to your Nextcloud server 
> • Download files from your Nextcloud server 
>  
> Feature plans for next releases: 
> • Move and rename files and folders 
> • Share your files and folders with others 
> • Managing shares 
> • Download directories as zip file 
> • Upload whole directories 
> • Monitor selected directories and upload new files in the background 
> • Synchronize selected directories in the background 
> • Instant Upload for photos and videos taken by your device 
> • Managing more than one user account / Nextcloud server (Multi-account support) 
> 
> Issues 
> 
> Please report all issues at https://github.com/nextcloud/windows-universal/issues 
> 
> New to Nextcloud? 
> 
> Nextcloud is a private file sync & share and communication server.  
It is fully open source and you can host it yourself or pay a company to do it for you.  
That way, you are in control of your photos, your calendar and contact data, your documents and everything else. 
> 
> Check out Nextcloud at https://nextcloud.com

## German version
> Dies ist die Nextcloud App, mit der Sie auf alle Ihre Dateien auf Windows Mobile (... und in Kürze auch UWP) zugreifen können. 
> 
> Um dieses Projekt auf dem Laufenden halten zu können und meine App-Store-Kosten sowie den Zeitaufwand zu kompensieren, beschloss ich einen Preis von 99 Cent zu verlangen. Wenn Sie das Geld nicht ausgeben wollen, können Sie den Quellcode von Github herunterladen und diese App selbst bauen & deployen, ohne Einschränkungen. Es ist alles Open Source. 
> 
> Bereits implementierte Funktionen: 
> • Einfache, moderne Benutzeroberfläche 
> • Dateien auf Ihrem Nextcloud Server hochladen 
> • Dateien von Ihrem Nextcloud Server herunterladen 
> 
> Geplant für nächste Versionen: 
> • Verschieben und Umbenennen von Dateien und Ordnern 
> • Teilen Ihrer Dateien und Ordner mit anderen 
> • Verwaltung von Shares 
> • Verzeichnisse als Zip-Datei herunterladen 
> • Upload ganzer Verzeichnisse 
> • Überwachen von ausgewählten Verzeichnissen und hochladen neuer Dateien im Hintergrund  
> • Synchronisieren von ausgewählten Verzeichnissen im Hintergrund 
> • Sofortiger Upload für Fotos und Videos, die von Ihrem Gerät aufgenommen wurden 
> • Verwalten von mehr als einem Benutzerkonto / Nextcloud Server (Multi-Account-Unterstützung) 
> 
> Probleme 
> 
> Bitte melden Sie alle Probleme unter https://github.com/nextcloud/windows-universal/issues 
> 
> Neu bei Nextcloud? 
> 
> Nextcloud ist ein privater Dateisynchronisierungs-, Dateifreigabe- und Kommunikationsserver. 
Die Serversoftware ist komplett Open Source und kann von Ihnen selbst oder von einer von Ihnen beauftragten Firma gehostet werden. So haben Sie die Kontrolle über Ihre Fotos, Ihren Kalender und Ihre Kontaktdaten, Ihre Dokumente und alles andere. 
> 
> Schauen Sie sich Nextcloud unter https://nextcloud.com an

**Comment by jospoortvliet** [comment]
Good from my pov.

**Comment by SunboX** [comment]
:sparkles: it has been published :sparkles:
